SEED = 1024
A_DOMAIN_CHANNEL = 3
B_DOMAIN_CHANNEL = 3
NGF = 64
NDF = 64

# train
EPOCHS = 20
BATCH_SIZE = 4
TRAIN_NUM_WORKERS = 8
TEST_NUM_WORKERS = 8

G_LR = 0.0002
G_BETAS = (0.5, 0.99)
D_LR = 0.0002
D_BETAS = (0.5, 0.99)
LR_DECAY_EPOCHS = 8

PRINT_FREQUENT = 0.001
EVAL_FREQUENT = 0.2

REAL_LABEL = 1
FAKE_LABEL = 0

USING_IDENTITY_LOSS = False
IDENTITY_LOSS_LAMBDA = 0.5
CYCLE_LOSS_LAMBDA_A = 10
CYCLE_LOSS_LAMBDA_B = 10

# data
# DATASET_ROOT = r"D:\dataset\edges2shoes"
DATASET_ROOT = r"/home/MyDisk3/YZJ/dataset/edges2shoes"
DATASET = "edge2shoes"

# output
CONSTANT_FEATURE_DIS_LEN = 4
OUTPUT_ROOT = "./output"
OUTPUT_MODEL_KEY = "model"
OUTPUT_LOG_KEY = "log"
OUTPUT_IMAGE_KEY = "images"
